name: "TEST"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      
jobs:
  run_build:
    name: "project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Update git"
        run: |
          ls -test
